#!/bin/sh
# check-ca-injection.sh — CI gate: every component this run actually resolved must
# inject the CA, using a local cert copy that's actually in sync with the real one at
# certs/<PLUGIN_CA_CERT_FILENAME>. Blocking, not advisory — unlike
# outbound-images-with-ca's escape-hatch Dockerfiles (auto-generated by default,
# hand-written only as a rare exception), EVERY Dockerfile here is hand-written, so
# nothing else catches a missing or stale CA block.
#
# PLUGIN_CA_CERT_FILENAME (default: cloudflare-origin-ca-rsa-root.pem) is the only
# place in this script the cert's filename is named — rename the actual file and set
# this one variable (in .woodpecker/build.yaml's `check-ca` step) to match; nothing
# else here needs editing. Each component's own Dockerfile still has to be updated by
# hand either way (its COPY source/destination literally names the file), and
# Woodpecker's own `when.path` entries in build.yaml are static YAML evaluated before
# any step runs — they can't read this or any other env var, so those stay literal
# strings that need editing by hand on a rename too.
#
# Scoped to PLUGIN_LOCATIONS_FILE (default: new_locations.txt) — the file the
# `version` step already writes via PLUGIN_OUTPUT_LOCATIONS_FILE, listing exactly
# which component(s) THIS run resolved to (already-implemented location resolution,
# not reimplemented here). A commit naming one location — feat[plugins/foo]: ... —
# checks only plugins/foo; breaking[**]: ... resolves to every component, so a mass
# rotation still checks all of them. If the file is empty or missing (nothing
# resolved this run), there's nothing to check.
#
# No exemption mechanism — every component in this repo injects the CA for real (see
# README "Every image here trusts the CA" for the three patterns in use, including
# the two kaniko plugins, which have no OS trust store at all and still manage it). A
# speculative "this one doesn't need it" escape hatch was considered and dropped:
# nothing in this repo has ever needed one, and an unused exemption is a silent,
# unreviewed way for a real gap to slip through later.
set -eu

CERT_FILENAME="${PLUGIN_CA_CERT_FILENAME:-cloudflare-origin-ca-rsa-root.pem}"
ROOT_CERT="certs/${CERT_FILENAME}"
LOCATIONS_FILE="${PLUGIN_LOCATIONS_FILE:-new_locations.txt}"
status=0

# Real injection is one of exactly these, matched only against actual RUN/COPY
# instruction lines (comments and unrelated text stripped first, below) — NOT a
# loose "does the cert filename appear anywhere" grep. A Dockerfile that only
# mentions the cert in a comment, or COPYs it somewhere inert, fails instead of
# incidentally passing:
#   - a real `RUN update-ca-trust` / `RUN update-ca-certificates` command
#   - a real `COPY` whose destination is a known OS trust-store path
#   - a real `RUN` appending into the known Alpine-style bundle file
REAL_INJECTION_PATTERNS='^RUN[[:space:]].*update-ca-trust
^RUN[[:space:]].*update-ca-certificates
^COPY[[:space:]].*[[:space:]]/etc/pki/ca-trust/source/anchors/
^COPY[[:space:]].*[[:space:]]/usr/local/share/ca-certificates/
^COPY[[:space:]].*[[:space:]]/kaniko/ssl/certs/
^RUN[[:space:]].*>>[[:space:]]*/etc/ssl/certs/ca-certificates\.crt'

if [ ! -s "$LOCATIONS_FILE" ]; then
    echo "ok: no locations resolved this run ($LOCATIONS_FILE empty or missing) — nothing to check."
    exit 0
fi

while IFS= read -r loc || [ -n "$loc" ]; do
    [ -n "$loc" ] || continue
    dockerfile="$loc/Dockerfile"

    if [ ! -f "$dockerfile" ]; then
        echo "FAIL: '$loc' was targeted this run but has no Dockerfile at $dockerfile"
        status=1
        continue
    fi

    real_instructions="$(grep -Ev '^[[:space:]]*(#|$)' "$dockerfile")"
    if ! printf '%s\n' "$real_instructions" | grep -Eq "$REAL_INJECTION_PATTERNS"; then
        echo "FAIL: $dockerfile does not actually inject the CA (a comment mentioning it"
        echo "      doesn't count, and neither does COPYing it somewhere that isn't a"
        echo "      known trust-store destination)."
        echo "      See README 'Every image here trusts the CA' for the patterns this"
        echo "      check accepts, including the two kaniko plugins' COPY into"
        echo "      /kaniko/ssl/certs/, with no OS trust store at all."
        status=1
        continue
    fi

    local_cert="$loc/${CERT_FILENAME}"
    if [ ! -f "$local_cert" ]; then
        echo "FAIL: $dockerfile injects the CA but $local_cert does not exist."
        status=1
        continue
    fi

    if ! cmp -s "$local_cert" "$ROOT_CERT"; then
        echo "FAIL: $local_cert is stale — it no longer matches $ROOT_CERT."
        echo "      On the next CA rotation this component will still build with the OLD"
        echo "      cert unless this copy is updated in the same commit as the root one."
        status=1
        continue
    fi

    echo "ok:   $dockerfile (CA injected, local copy in sync with root)"
done < "$LOCATIONS_FILE"

exit "$status"
