#!/bin/sh
# check-ca-injection.sh — CI gate: every component's Dockerfile must inject the CA,
# using a local cert copy that's actually in sync with certs/cloudflare-origin-ca-rsa-root.pem.
# Blocking, not advisory — unlike outbound-images-with-ca's escape-hatch Dockerfiles
# (auto-generated by default, hand-written only as a rare exception), EVERY Dockerfile
# here is hand-written, so nothing catches a missing/forgotten CA block except this.
#
# No exemption mechanism — every one of the 15 components today injects the CA for
# real (see README "Every image here trusts the CA" for the three patterns in use,
# including the two kaniko plugins, which have no OS trust store at all and still
# manage it). A speculative "this one doesn't need it" escape hatch was considered and
# dropped: nothing in this repo has ever needed one, and an unused exemption is a
# silent, unreviewed way for a real gap to slip through later. If a genuine
# no-CA-possible case ever shows up, add the check for it then, against the real
# constraint — not against a guess made before one existed.
set -eu

ROOT_CERT="certs/cloudflare-origin-ca-rsa-root.pem"
status=0

for dockerfile in base/*/Dockerfile plugins/*/Dockerfile; do
    [ -f "$dockerfile" ] || continue
    dir="$(dirname "$dockerfile")"

    if ! grep -qi "cloudflare-origin-ca\|update-ca-certificates\|update-ca-trust" "$dockerfile"; then
        echo "FAIL: $dockerfile does not inject the CA."
        echo "      See README 'Every image here trusts the CA' for the three patterns"
        echo "      already in use (including the two kaniko plugins, which have no OS"
        echo "      trust store at all and still manage it)."
        status=1
        continue
    fi

    local_cert="$dir/cloudflare-origin-ca-rsa-root.pem"
    if [ ! -f "$local_cert" ]; then
        echo "FAIL: $dockerfile injects the CA but $local_cert does not exist."
        status=1
        continue
    fi

    if ! cmp -s "$local_cert" "$ROOT_CERT"; then
        echo "FAIL: $local_cert is stale — it no longer matches $ROOT_CERT."
        echo "      On the next CA rotation this component will still build with the OLD"
        echo "      cert unless this copy is updated in the same commit as the root one."
        status=1
        continue
    fi

    echo "ok:   $dockerfile (CA injected, local copy in sync with root)"
done

exit "$status"
