#!/bin/sh
# check-ca-injection.sh — CI gate: every component this run actually resolved must
# inject the CA using the one generic, distro-detecting injector every Dockerfile in
# this repo shares (scripts/inject-ca.sh) — using a local cert copy that's actually in
# sync with the real one at certs/<PLUGIN_CA_CERT_FILENAME>, AND a local injector copy
# in sync with scripts/<PLUGIN_CA_INJECTOR_FILENAME>. Blocking, not advisory — unlike
# outbound-images-with-ca's escape-hatch Dockerfiles (auto-generated by default,
# hand-written only as a rare exception), EVERY Dockerfile here is hand-written, so
# nothing else catches a missing or stale CA block.
#
# Because every Dockerfile now uses the SAME generic injector instead of hand-picking
# a distro-specific mechanism (update-ca-trust vs. update-ca-certificates vs.
# append-to-bundle vs. kaniko's SSL_CERT_DIR — inject-ca.sh detects and handles all
# four itself), this check only ever has ONE pattern to verify, not a menu of
# alternatives: a real COPY of the cert, a real COPY of the injector, and a real RUN
# of it. A Dockerfile author never needs to know or investigate which trust-store
# mechanism their particular base image needs — the injector figures it out at build
# time; this check only confirms the three lines that hand off to it are actually
# there for real, not just mentioned in a comment.
#
# PLUGIN_CA_CERT_FILENAME (default: cloudflare-origin-ca-rsa-root.pem) and
# PLUGIN_CA_INJECTOR_FILENAME (default: inject-ca.sh) are the only places this script
# names either file — rename either actual file and set the matching variable (in
# .woodpecker/build.yaml's `check-ca` step) to match; nothing else here needs editing.
# Each component's own Dockerfile still has to be updated by hand either way (its COPY
# source/destination literally names the file), and Woodpecker's own `when.path`
# entries in build.yaml are static YAML evaluated before any step runs — they can't
# read this or any other env var, so those stay literal strings that need editing by
# hand on a rename too.
#
# Scoped to PLUGIN_LOCATIONS_FILE (default: new_locations.txt) — the file the
# `version` step already writes via PLUGIN_OUTPUT_LOCATIONS_FILE, listing exactly
# which component(s) THIS run resolved to (already-implemented location resolution,
# not reimplemented here). A commit naming one location — feat[plugins/foo]: ... —
# checks only plugins/foo; breaking[**]: ... resolves to every component, so a mass
# rotation still checks all of them. If the file is empty or missing (nothing
# resolved this run), there's nothing to check.
#
# No exemption mechanism — every component in this repo injects the CA for real. A
# speculative "this one doesn't need it" escape hatch was considered and dropped:
# nothing in this repo has ever needed one, and an unused exemption is a silent,
# unreviewed way for a real gap to slip through later.
set -eu

CERT_FILENAME="${PLUGIN_CA_CERT_FILENAME:-cloudflare-origin-ca-rsa-root.pem}"
INJECTOR_FILENAME="${PLUGIN_CA_INJECTOR_FILENAME:-inject-ca.sh}"
ROOT_CERT="certs/${CERT_FILENAME}"
ROOT_INJECTOR="scripts/${INJECTOR_FILENAME}"
LOCATIONS_FILE="${PLUGIN_LOCATIONS_FILE:-new_locations.txt}"
status=0

if [ ! -s "$LOCATIONS_FILE" ]; then
    echo "ok: no locations resolved this run ($LOCATIONS_FILE empty or missing) — nothing to check."
    exit 0
fi

while IFS= read -r loc || [ -n "$loc" ]; do
    [ -n "$loc" ] || continue
    dockerfile="$loc/Dockerfile"

    if [ ! -f "$dockerfile" ]; then
        echo "FAIL: '$loc' was targeted this run but has no Dockerfile at $dockerfile"
        status=1
        continue
    fi

    real_instructions="$(grep -Ev '^[[:space:]]*(#|$)' "$dockerfile")"

    if ! printf '%s\n' "$real_instructions" | grep -Eq "^COPY[[:space:]].*${CERT_FILENAME}"; then
        echo "FAIL: $dockerfile has no real COPY of ${CERT_FILENAME} (a comment mentioning"
        echo "      it doesn't count). See README for the required Dockerfile shape."
        status=1
        continue
    fi

    if ! printf '%s\n' "$real_instructions" | grep -Eq "^COPY[[:space:]].*${INJECTOR_FILENAME}"; then
        echo "FAIL: $dockerfile has no real COPY of ${INJECTOR_FILENAME}."
        status=1
        continue
    fi

    if ! printf '%s\n' "$real_instructions" | grep -Eq "^RUN[[:space:]].*sh[[:space:]].*${INJECTOR_FILENAME}"; then
        echo "FAIL: $dockerfile COPYs ${INJECTOR_FILENAME} but never RUNs it."
        status=1
        continue
    fi

    local_cert="$loc/${CERT_FILENAME}"
    if [ ! -f "$local_cert" ]; then
        echo "FAIL: $dockerfile injects the CA but $local_cert does not exist."
        status=1
        continue
    fi
    if ! cmp -s "$local_cert" "$ROOT_CERT"; then
        echo "FAIL: $local_cert is stale — it no longer matches $ROOT_CERT."
        echo "      On the next CA rotation this component will still build with the OLD"
        echo "      cert unless this copy is updated in the same commit as the root one."
        status=1
        continue
    fi

    local_injector="$loc/${INJECTOR_FILENAME}"
    if [ ! -f "$local_injector" ]; then
        echo "FAIL: $dockerfile injects the CA but $local_injector does not exist."
        status=1
        continue
    fi
    if ! cmp -s "$local_injector" "$ROOT_INJECTOR"; then
        echo "FAIL: $local_injector is stale — it no longer matches $ROOT_INJECTOR."
        echo "      A fix or new distro case added to the canonical injector won't reach"
        echo "      this component's build until its own copy is refreshed."
        status=1
        continue
    fi

    echo "ok:   $dockerfile (CA injected via the generic injector, both local copies in sync)"
done < "$LOCATIONS_FILE"

exit "$status"
